application: zenusage
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /index.html
  static_files: root/index.html
  upload: root/index.html

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /app
  static_dir: app

- url: /webservices.*
  script: webservices/services.py
  # secure: always?

- url: /protorpc.*
  script: webservices/services.py
  # secure: always?
