application: zenusage
version: 1
runtime: python
api_version: 1

handlers:
- url: /app
  static_dir: app

- url: /styles
  static_dir: styles

- url: /images
  static_dir: images

- url: /lib
  static_dir: lib

- url: /demo
  static_dir: demo

- url: /webservices.*
  script: webservices/services.py
  # secure: always

- url: /protorpc.*
  script: webservices/services.py
  # secure: always?

